### PR TITLE
Added Scala 2.12.1 for crossbuilding. Fixed dependencies as necessary.

### PR DESCRIPTION
**Pull request by orendain**
Addresses issue: https://github.com/ua-parser/uap-scala/issues/13

### CODE REVIEW

**Comment by vitorsvieira** [comment]
@humanzz @aoiroaoino @orendain Is this library still maintained?

**Comment by orendain** [comment]
@vitorsvieira I'm successfully using uap-scala, though don't have enough bandwidth to track down and patch the failed test.  I'm not sure if the project as a whole is still actively maintained (or if it even needs it) - the day I submitted the PR was the first day I stumbled upon this repo.

**Comment by travisbrown** [comment]
@orendain @vitorsvieira I've taken a slightly different approach in #18.

**Comment by humanzz** [comment]
Merged https://github.com/ua-parser/uap-scala/pull/18

**Pull request closed without merging**
