### PR TITLE
Feature/update to latest core

### PR DESCRIPTION
**Pull request by belerophon**
Hi!

This pull request tries to make all tests pass using the latest `core`.

The `Device.scala` was reviewed and altered using [this](https://github.com/lefloh/uap-java/blob/master/src/main/java/ua_parser/DeviceParser.java) as a reference.

What do you think?

### CODE REVIEW

**Comment by mcveat** [comment]
Hi @belerophon . Thanks for your PR. I'm going to take a closer look at it in a week or two, when I find some time.

**Comment by belerophon** [comment]
Hey @mcveat can you give me some idea of when you'll be able to look at the pull request?

Thanks!

**Comment by mcamenzind** [comment]
@mcveat: Is this still maintained? If so, please accept pull request, otherwise look for maintainer.

**Comment by humanzz** [comment]
I've updated the library to use the latest core a couple of days ago.

**Pull request closed without merging**
