### PR TITLE
Update uap-core to latest master commit

### PR DESCRIPTION
**Pull request by jleider**

### CODE REVIEW

**Comment by jleider** [comment]
I dont know why these tests are failing since the actual uap-core tests all pass.

uap-core: `node run test`
```
npm run test                       04/21 11:34:07 0.002s

> uap-core@0.5.0 test /src/uap-scala/core
> mocha -u tdd -R min ./tests/test.js

  30459 passing (8s)
```

uap-scala: `sbt test`
```
> test
[info] CachingParserSpec
[info]
[info] Parser should
[info] + parse basic ua
[info] + properly quote replacements
[info] + properly parse user agents
[info] + properly parse os
[info] x properly parse device
[error]    'Device(iOS-Device,Some(Apple),Some(iOS-Device))'
[error]
[error]     is not equal to
[error]
[error]    'Device(Other,None,None)' (ParserSpecBase.scala:70)
[info]
[error] Expected: Device(Other,None,None)
[info]
[error] Actual:   Device(iOS-Device,Some(Apple),Some(iOS-Device))
[info]
[info]
[info]
[info] Total for specification CachingParserSpec
[info] Finished in 50 seconds, 647 ms
[info] 5 examples, 14269 expectations, 1 failure, 0 error
[info]
[info] ParserSpec
[info]
[info] Parser should
[info] + parse basic ua
[info] + properly quote replacements
[info] + properly parse user agents
[info] + properly parse os
[info] x properly parse device
[error]    'Device(iOS-Device,Some(Apple),Some(iOS-Device))'
[error]
[error]     is not equal to
[error]
[error]    'Device(Other,None,None)' (ParserSpecBase.scala:70)
[info]
[error] Expected: Device(Other,None,None)
[info]
[error] Actual:   Device(iOS-Device,Some(Apple),Some(iOS-Device))
[info]
[info]
[info]
[info] Total for specification ParserSpec
[info] Finished in 50 seconds, 770 ms
[info] 5 examples, 14269 expectations, 1 failure, 0 error
[info]
[error] Failed: Total 10, Failed 2, Errors 0, Passed 8
[error] Failed tests:
[error] 	org.uaparser.scala.ParserSpec
[error] 	org.uaparser.scala.CachingParserSpec
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 52 s, completed Apr 21, 2017 11:31:38 AM
```

**Comment by jleider** [comment]
https://github.com/ua-parser/uap-core/issues/239 fixes the scala test failure. I will update this PR as soon as that update is merged into uap-core.

**Comment by jleider** [comment]
The PR for uap-core is no longer required as I have updated this PR to reflect the expected behavior of the uap-core tests and functionality.

**Comment by humanzz** [comment]
I've updated to latest uap-core in https://github.com/ua-parser/uap-scala/commit/a874af143be140d60822478da5b73548b0647889

**Pull request closed without merging**
