### PR TITLE
Add parallel parsing method for Parser

### PR DESCRIPTION
**Pull request by Solodye**
performance_issue

Hi Maintainer

According to the unit test results, there may be some performance issue when it is used in the Big data processing scenario as UDF.

The only way I can come up with is to use Future to make it parallel.

Kindly review it. thanks.

### CODE REVIEW

**Comment by phucnh** [comment]
@Solodye I think we can implement the parallel parsing without introducing a new API like the following example:
```scala
val parser = Parser.default

def parParser(parser: Parser, agent: String): Future[Client] = {
  val clientFuture = for {
    ua <- Future { parser.userAgentParser(agent) }
    os <- Future {osParser.parse(agent)}
    dv <- Future {deviceParser.parse(agent)}
  } yield Client(ua, os, dv)
}
```

You can also use the [Pimp my library pattern](https://www.artima.com/weblogs/viewpost.jsp?thread=179766) to extend the `Parser` API.
From the library perspective, I think we shouldn't depend on a specific concurrent model (e,g. `Future`) if possibles,
as well as shouldn't use the global execution context which can be set by developers.

**Comment by Solodye** [comment]
Hi @phucnh 
Thanks for providing the example and share your opinion.

There is a problem with your example. We should not generate Future in the `for` comprehension due to it is just syntactic sugar. Otherwise, it will run sequentially. Can refer:  https://stackoverflow.com/questions/19045936/scalas-for-comprehension-with-futures

Spark project also uses `Future` and `ExecutionContext.Implicits.global` and it is a great fundamental tool. However, to reduce the dependency as much as possible may be a good idea to avoid the possible issue when other developer uses it. I didn't think about this before, thanks for your opinion.

**Comment by Solodye** [comment]
But at least, I think this time cost issue and the internal parsing interface need to let other developers know, can review https://github.com/ua-parser/uap-scala/pull/150

**Comment by phucnh** [comment]
@Solodye Sorry for my missing an example, the Future should not be created inside `for`. Thank you for pointing it out.

**Pull request closed without merging**
